name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: cross build --release --target ${{ matrix.target }}
        env:
          CARGO_BUILD_JOBS: 2

      - name: Rename binary
        run: |
          if [ "${{ matrix.target }}" = "x86_64-unknown-linux-musl" ]; then
            cp target/${{ matrix.target }}/release/ottershipper ottershipper-linux-x86_64
          elif [ "${{ matrix.target }}" = "aarch64-unknown-linux-musl" ]; then
            cp target/${{ matrix.target }}/release/ottershipper ottershipper-linux-aarch64
          fi

      - name: Generate checksums
        run: |
          sha256sum ottershipper-linux-* > SHA256SUMS
          cat SHA256SUMS

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ottershipper-linux-*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload checksums to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: SHA256SUMS
          tag: ${{ github.ref }}
          overwrite: true
